// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyVbHRF6Rr1-dpjke1GCgqmehiY67caBU',
    appId: '1:359416259539:web:e3c751b033b8f89c4e0526',
    messagingSenderId: '359416259539',
    projectId: 'hospedaje-f1',
    authDomain: 'hospedaje-f1.firebaseapp.com',
    storageBucket: 'hospedaje-f1.firebasestorage.app',
    measurementId: 'G-NVVWBVNPJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3fkZppiWy880gYzVWvo3Hqok_t7guM6c',
    appId: '1:359416259539:android:5fa125fbacf0a3004e0526',
    messagingSenderId: '359416259539',
    projectId: 'hospedaje-f1',
    storageBucket: 'hospedaje-f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMzt3b0K6_SrdwWshOju3KNOH-qpUFDSw',
    appId: '1:359416259539:ios:8b6ec555d6947d714e0526',
    messagingSenderId: '359416259539',
    projectId: 'hospedaje-f1',
    storageBucket: 'hospedaje-f1.firebasestorage.app',
    iosBundleId: 'com.example.flutterHospedajef1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMzt3b0K6_SrdwWshOju3KNOH-qpUFDSw',
    appId: '1:359416259539:ios:8b6ec555d6947d714e0526',
    messagingSenderId: '359416259539',
    projectId: 'hospedaje-f1',
    storageBucket: 'hospedaje-f1.firebasestorage.app',
    iosBundleId: 'com.example.flutterHospedajef1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyVbHRF6Rr1-dpjke1GCgqmehiY67caBU',
    appId: '1:359416259539:web:7a41431b9db537f34e0526',
    messagingSenderId: '359416259539',
    projectId: 'hospedaje-f1',
    authDomain: 'hospedaje-f1.firebaseapp.com',
    storageBucket: 'hospedaje-f1.firebasestorage.app',
    measurementId: 'G-YYW5J1Z9LR',
  );

}